### ISSUE TITLE
"Adwaita" theme support

### ISSUE THREAD

**Issue by mz1193** [themix-project/themix-gui#167]
Would it be possible to add support for the Adwaita theme? I generally enjoy the look and feel of it, and I'd love to be able to easily colourize it. Thank you.

**Comment by actionless** [comment]
the best starting points for writing new themix plugin:

1) PR for Arc theme as example of color-changing support on theme side: https://github.com/NicoHood/arc-theme/pull/101

2) themix plugin for Arc theme: https://github.com/themix-project/oomox/tree/master/plugins/theme_arc

**Comment by actionless** [comment]
@theamazing0 yeah, i'm not against merging a plugin for compatibility with that tool, see instructions above on how to develop it

**Comment by actionless** [comment]
bwt forgot to mention that Adwaita-GTK4 is actually supported, mb someone would like to contribute a similar code for Adwaita GTK3 and GTK2:

https://github.com/themix-project/themix-plugin-base16/tree/master/templates_extra/gtk4/templates
