### ISSUE TITLE
Oomox CLI revamp

### ISSUE THREAD

**Issue by actionless** [themix-project/themix-gui#202]
Current CLI scripts are just links to change_color.sh scripts inside each plugin itself,

New CLI should have one entry point and reuse plugin-loader from oomox_gui.

New CLI will have 2 actions:
 - `export` (for `theme`,`icons` and `export` plugins)
 - `import` (for `import` plugins :) )

and 4 arguments:
 - `--preset` -- path to themix colorscheme;
 - `--plugin` -- name of the plugin to use, ie dir name like here: https://github.com/themix-project/oomox/tree/master/plugins;
 - `--export-opts` (or just `--opts`?) - comma-separated list of export options (`--export-opts key1=value1,key2=value2`), keys and values should be like in `~/.config/oomox/export_config/*.json` files.
 - [optional] `--override` - comma-separated list of theme values/options (`--override BG=ff0000,BASE16_GENERATE_DARK=True`), keys and values should be like in themix/oomox theme model

Please leave any comments/feedback before the work on it will start.

**Comment by b1scu1t** [comment]
I see you can export color schemes in the GUI for `xresources` `rofi` and other programs.
Possibly we could expose that output through the CLI?

Or maybe, the program can accept regular text files as templates with key-values to be replaced?

I'm thinking something like [WPGTK](https://github.com/deviantfero/wpgtk).
Its another Python 3 application to generate themes for GTK, rofi, or any template you feed it. It simple but quick.

[Warni](https://github.com/reorr/warnai) is another one, but I'm not too familiar with that...

**Comment by actionless** [comment]
you already can use base16-template for any app, only CLI for it not implemented

base16 templates are pre-installed using collection from here (https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml) but if you wanna have the options for adding user-defined templates under ~/.config/oomox/ feel free to create a separate ticket for that

**Comment by actionless** [comment]
now CLI was implemented as well:
https://github.com/themix-project/themix-plugin-base16/commit/ef12a9017155f2e47915338e292d7e64f90ff954

**Comment by FragCGI** [comment]
Any word on the CLI doing icon themes yet? I need it for ricing. :rofl:

**Comment by actionless** [comment]
@FragCGI the CLI for icons was always there and working, this ticket about revamping all CLIs under one single entry point (`themix-cli`) instead of individual CLIs

**Comment by FragCGI** [comment]
@actionless well, I guess I had been looking in the wrong places because I haven't been able to figure that one out. Time to keep searching.

**Comment by FragCGI** [comment]
Been there, still can't figure out the syntax to get icons based on xresources, more specifically xresources reverse. The theme was easy, but this icon export is killing me. I'm sure I'll figure it out with time though.

**Comment by actionless** [comment]
it's described in this, same-called, paragraph... https://github.com/themix-project/themix-gui#cli

**Comment by actionless** [comment]
fixed in https://github.com/themix-project/themix-gui/commit/86cb6d7816ef728e221dccc6a676050cb239d063
