### ISSUE TITLE
Export to Kvantum

### ISSUE THREAD

**Issue by null-von-sushi** [themix-project/themix-gui#242]
Would it be possible for oomox to also export a kvantum theme? For example, I am trying to change ARC to have red accent colors instead, which works for GTK-based applications, however it doesn't work for QT.

**Comment by actionless** [comment]
everything is possible but i am not using KDE myself so i could only assist to some KDE user to implement it

**Comment by null-von-sushi** [comment]
Oh I see. Unfortunately while I'd be willing to help, I don't really know actual programming sorry.

Thanks for willing to include it though.

**Comment by csehszlovakze** [comment]
[Here](https://drive.google.com/drive/folders/1_SQTnr2YUSvfiFN9uK62TP3-4sQcIIh5) is an example for a Kvantum theme. It consists of a config file, a colors file and an SVG file making up the bulk of it.

I see a huge potential in combining the power of the two theme engines for a unified look and feel.

**Comment by actionless** [comment]
i think it can be bootstrapped as a copy of [base16 plugin](https://github.com/themix-project/oomox/tree/master/plugins/base16) which also converts hex colors into rgb components

**Comment by actionless** [comment]
or alternatively it can be done as part of oomox-gtk-theme, https://github.com/themix-project/oomox-gtk-theme/issues/55

**Comment by MissLav** [comment]
> [Here](https://drive.google.com/drive/folders/1_SQTnr2YUSvfiFN9uK62TP3-4sQcIIh5) is an example for a Kvantum theme. It consists of a config file, a colors file and an SVG file making up the bulk of it.
> 
> I see a huge potential in combining the power of the two theme engines for a unified look and feel.

btw the link is dead

i would love kde support since im trying to swap to it due to steam os 3.0 using it and id like to get used to themeing kde

**Comment by MissLav** [comment]
wait no the link wasn't dead it was just my user agent switcher listing an outdated version of firefox

**Comment by actionless** [comment]
recently new templating engine started being developed as a plugin by @The-Repo-Club : 

https://github.com/The-Repo-Club/oomox
https://github.com/The-Repo-Club/oomox-templates


the old way is using standard mechanism used for gtk themes etc:
https://github.com/themix-project/oomox-gtk-theme/blob/master/src/qt6ct_palette.conf

**Comment by MissLav** [comment]
> recently new templating engine started being developed as a plugin by @The-Repo-Club :
> 
> https://github.com/The-Repo-Club/oomox
> https://github.com/The-Repo-Club/oomox-templates
> 
> the old way is using standard mechanism used for gtk themes etc:
> https://github.com/themix-project/oomox-gtk-theme/blob/master/src/qt6ct_palette.conf

oh? how would one make use of this

**Comment by The-Repo-Club** [comment]
I'll have a arch install file made up for it as soon as I get it completed :)

**Comment by actionless** [comment]
> oh? how would one make use of this

if you're a kde user, you could use one of proposed ways to contribute the template for your wm

**Comment by MissLav** [comment]
> > oh? how would one make use of this
> 
> if you're a kde user, you could use one of proposed ways to contribute the template for your wm

oh im an xfce user but like i said im trying to learn kde due to steam os 3.0 using it and Im going to get a steam deck

**Comment by MissLav** [comment]
but eyah i can help test

**Comment by actionless** [comment]
implemented in `base16` plugin

**Comment by lavenderdotpet** [comment]
nice  👍

**Comment by DIMFLIX-OFFICIAL** [comment]
> implemented in `base16` plugin

Please tell me how to use it. I can't find an export to kvantum... It is not in base16 templates

**Comment by actionless** [comment]
because depending of if you use kde or not, you configure it either via `kde` settings or via `qt{5,6}ct`
