### ISSUE TITLE
Home directory shown as empty in Open file dialog

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [themix-project/themix-gui#256]
OS: Linux Mint 19.1, Cinnamon 64 bit

I recently installed oomox via the software manager and it is generally working great.

However, when I click on Import -> Colors from Image and select my Home directory (both via the bookmark in the top-left corner and by navigation to /home/<user>/) it is shown as empty. This is happening on my desktop as well as my notebook (both running the same os).

I tried copying an image into /home, but while the <user> folder does show up there, the image does not.

Any idea why this is happening?

**Comment by actionless** [comment]
could you please submit a screenshot to make me easier to understand/reproduce the problem?

**Comment by Adrian-Bielefeldt** [comment]
![Screenshot from 2019-08-11 01-53-47](https://user-images.githubusercontent.com/21172799/62827925-f63d7c00-bbda-11e9-85ab-4d8fa4ddf303.png)

As you can see, my home directory isn't empty. But it shows up as empty in the "Please choose an image file" dialog.

**Comment by actionless** [comment]
weird, i'm doing the same, but they showing up:

![2019-08-11--1565481486_1807x1393_scrot](https://user-images.githubusercontent.com/1655669/62827945-7ebc1c80-bbdb-11e9-8725-4506cc17324e.png)


could you try running oomox-gui from the terminal and see if there are any error messages shown?

**Comment by Adrian-Bielefeldt** [comment]
This is the only output I get when running oomox from the terminal:

!! WARNING !! 'pystache' and 'python-yaml' need to be installed for exporting Base16 themes

(__main__.py:2): dconf-WARNING **: 23:27:49.900: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

**Comment by actionless** [comment]
what GTK version do you have?

**Comment by actionless** [comment]
could you also try opening file dialog in `Meld` app?

**Comment by Adrian-Bielefeldt** [comment]
For GTK2 I have 2.24.32-1ubuntu1 and for GTK3 3.22.30-1ubuntu4.

I can browse my home directory without any issue in Meld.
