### ISSUE TITLE
Add support for Stumpwm

### ISSUE THREAD

**Issue by OrionRandD** [themix-project/themix-gui#283]
Hi,
Great app. Could you add support for
Stumpwm TW?
https://github.com/stumpwm/stumpwm
https://archive.org/details/TheStumpWMExperience

**Comment by actionless** [comment]
i'm not using that WM so not

but contributions are welcome

you can do it either as an oomox plugin (https://github.com/themix-project/oomox/tree/master/plugins) or as a base16 template (https://github.com/chriskempson/base16-templates-source))

**Comment by Th3Whit3Wolf** [comment]
I don't use stumpwm either but what's not working? Is oomox crashing or are you unable to use the gtk themes oomox produces?

**Comment by actionless** [comment]
@Th3Whit3Wolf  i think the reporter asks to generate a theme for the WM itself

**Comment by actionless** [comment]
https://github.com/themix-project/themix-plugin-base16/tree/master/templates/stumpwm/templates
