### ISSUE TITLE
Flatpak build needs a maintainer

### ISSUE THREAD

**Issue by actionless** [themix-project/themix-gui#394]
Themix / Oomox apps having few small changes here and there so it would be nice to push the release to Flatpak from time to time.

However the build require maintenance over time (like updating the versions of deps and so on), and since i'm not using Flatpak myself it stays outdated for more than a year from now.

**Comment by HugLifeTiZ** [comment]
GNOME has decided themes should die, and I want to be part of the resistance that supports theming in other GTK-based environments. I think oomox is important toward that, and making sure non-GNOME and non-Elementary GTK applications exist in Flathub is also important toward that. I also think that Flatpak is good technology that deserves support, but it also needs people contributing to it that aren't catering exclusively to the needs of GNOME.

Sign me up.

**Comment by HugLifeTiZ** [comment]
Sure. There hasn't been a release of oomox since 1.13.3 though. Are you planning to make one?

**Comment by actionless** [comment]
the only remaining release channel is aur, which builds from git - so there was no much reason to tag it, but i'm aware what flatpak is building only from tag (or at least it was the case some years ago) - so i can make a tag no problem at all

**Comment by actionless** [comment]
damn, i just realized what i dont have permissions myself to add maintainers to that repo as it part of flathub org, i'll try to find the contact channel of theirs

**Comment by actionless** [comment]
@HugLifeTiZ i've created a ticket in their repo, hope it gonna help to clarify the right way to do it (i didn't found anything in the docs/existing issues)

**Comment by actionless** [comment]
btw just a side note, @HugLifeTiZ , flatpak package currently have all 3 GTK themes, Arc, Materia and Oomox.
updating `libsass` would break Arc (but that should happen sooner or later - as it's deprecated by now), and updating `resvg` could break at least Materia (recent releases seems to build only with Inkscape but not resvg) but also Arc mb too.

**Comment by HugLifeTiZ** [comment]
Thank you for the heads up, seems that is something I'll want to test. RIP Arc.

**Comment by actionless** [comment]
@HugLifeTiZ arc itself is alive but new maintainers decided to move in a direction in which they couldnt continue maintaining support for themox plugin

**Comment by HugLifeTiZ** [comment]
Ah, that's unfortunate. Is the intent to support the old version of Arc for as long as is feasible? Has the oomox theme itself received updates that are not currently in the flatpak? What should be the preference for Materia? Keep old version to build with resvg, or try to find a way to build the new version? I notice that imagemagick is built as part of oomox, maybe it can be used.

**Comment by actionless** [comment]
Oomox theme have some small fixes here and there, icons have lots of updates especially Papirus which adding new icons almost every day

Materia - the particular problem what at some point GTK2 theme started to look broken with resvg - but i'm not sure at which point of time that happened, and if it was the result of resvg update, materia or both - because officially materia supports only inkscape i've decided for time being to stick to that on other platforms

regarding Arc - i never used it myself much so not care about it at all, it was just quite easy to add initially and a lot of people asked for that

**Comment by actionless** [comment]
i see you finally got added to flathub repo

another good update what new release is almost ready to be merged into master: https://github.com/themix-project/oomox/pull/403

**Comment by HugLifeTiZ** [comment]
Yep, I'm finally in there. Should I wait for that to get merged and the release made before I update the Flathub package, or should I go ahead and work on that now using that branch?

**Comment by actionless** [comment]
better already start with that branch - release itself is ready on code - it only missing the packaging update for arch linux and testing of it (because xresources_export moved to separate plugin)
