### ISSUE TITLE
info needed: No plugins installed for "Icons Style" / "Style for UI elements"

### ISSUE THREAD

**Issue by Ryder17z** [themix-project/themix-gui#464]
I don't get it ?

I only installed this in attempt to stylize papirus-dark.

**Comment by actionless** [comment]
make sure you followed installation instructions in the https://github.com/themix-project/themix-gui#readme correctly

**Comment by Ryder17z** [comment]
Did follow aur instructions though...

**Comment by actionless** [comment]
> Did follow aur instructions though...

https://github.com/themix-project/themix-gui#arch-linux ?

**Comment by Ryder17z** [comment]
Yes.

**Comment by actionless** [comment]
doesn't look realistic to me, you prolly missing smth, try over again

**Comment by Ryder17z** [comment]
Nothing missed. just oddball behavior from a dying drive. (it seemed fine until now. x11 doesn't start and /var/ is just gone among other things)

RMA Time...

**Comment by actionless** [comment]
you might laugh, but up to half of themix issues are related to reporter's filesystem problems
