### ISSUE TITLE
bug: oomox-cli throws `Error patching extheme.dll`

### ISSUE THREAD

**Issue by onemoresuza** [themix-project/themix-gui#474]
# Description
Running `oomox-cli` on any of the Xresources themes --- `/opt/oomox/scripted_colors/xresources/` --- results in the following message being shown `Error patching uxtheme.dll`. Although the compilation messages appear as if no problem has occurred, both GTK --- _e. g._, Firefox, Chromium, pinentry-gtk-2 --- and QT --- pientry-qt --- programs are unable to pick up the generated theme.

# To Reproduce

`oomox-cli /opt/oomox/scripted_colors/xresources/<theme>`

being `<theme>` any of the following:
1. xresources
2. xresources-reverse
3. xresources2
4. xresources3

# Output
## STDOUT
With the `xresources3` theme:

> 
> 
> Error patching uxtheme.dll
> 
> 
> 
> Building theme at /home/\<userhome\>/.themes/oomox-xresources3
> 
> make clean_gtk3
> make clean_gtk320
> sassc -I "cinnamon/scss" "cinnamon/scss/cinnamon.scss" "cinnamon/cinnamon.css"
> make[1]: Entering directory '/home/\<userhome\>/.themes/oomox-xresources3'
> rm -rf "gtk-3.0/dist"
> make[1]: Entering directory '/home/\<userhome\>/.themes/oomox-xresources3'
> rm -rf "gtk-3.20/dist"
> rm -f "gtk-3.0/gtk.gresource"
> rm -f "gtk-3.20/gtk.gresource"
> make[1]: Leaving directory '/home/\<userhome\>/.themes/oomox-xresources3'
> make[1]: Leaving directory '/home/\<userhome\>/.themes/oomox-xresources3'
> make gresource_gtk3
> make gresource_gtk320
> make[1]: Entering directory '/home/\<userhome\>/.themes/oomox-xresources3'
> mkdir -p "gtk-3.0/dist"
> make[1]: Entering directory '/home/\<userhome\>/.themes/oomox-xresources3'
> mkdir -p "gtk-3.20/dist"
> sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk.scss" "gtk-3.0/dist/gtk.css"
> sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
> cp "gtk-3.20/dist/gtk.css" "gtk-3.20/dist/gtk-dark.css"
> glib-compile-resources --sourcedir="gtk-3.20" "gtk-3.20/gtk.gresource.xml"
> cp "gtk-3.0/dist/gtk.css" "gtk-3.0/dist/gtk-dark.css"
> glib-compile-resources --sourcedir="gtk-3.0" "gtk-3.0/gtk.gresource.xml"
> make[1]: Leaving directory '/home/\<userhome\>/.themes/oomox-xresources3'
> make[1]: Leaving directory '/home/\<userhome\>/.themes/oomox-xresources3'

# System
`uname -a` output:

> Linux \<hostname\> 6.2.8-arch1-1 #\1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux

**Comment by Ivordir** [comment]
`if [[ $(date +"%m%d") = "0401" ]] && [[ -z "${no_jokes:-}" ]] ; then`
I'm mad but and at the same time not mad...

**Comment by barbiefan** [comment]
spent a couple of hours figuring out what the issue was.
thanks OSS, very funny.

**Comment by onemoresuza** [comment]
The problem seems to be fixed now.

**Comment by golam71** [comment]
@onemoresuza  how did you fix it can u explain?
i am on archlinux i still have this issue

**Comment by barbiefan** [comment]
> @onemoresuza how did you fix it can u explain? i am on archlinux i still have this issue

it checks for env var "no_jokes", so set it to 1 before running the script (or gui)

**Comment by VinAreXav** [comment]
bruh :0

**Comment by barbiefan** [comment]
lmao still getting comments in the big 2026
