### ISSUE TITLE
Can't export ARC theme.

### ISSUE THREAD

**Issue by cargl** [themix-project/themix-gui#480]
![image](https://github.com/themix-project/themix-gui/assets/85845418/79b8684d-e795-4c3c-86eb-d25e3e9c9268)
`(__main__.py:181191): Gtk-WARNING **: 23:27:59.209: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Inhibit”
Can't read config file
[Errno 2] No such file or directory: '/home/wao/.config/oomox/export_config/arc_theme.json'
Traceback (most recent call last):
  File "/home/wao/Documents/oomox/oomox_gui/export_common.py", line 129, in <lambda>
    self.apply_button.connect("clicked", lambda _x: self.do_export())
                                                    ^^^^^^^^^^^^^^^^
  File "/home/wao/Documents/oomox/plugins/theme_arc/oomox_plugin.py", line 52, in do_export
    super().do_export()
  File "/home/wao/Documents/oomox/oomox_gui/export_common.py", line 362, in do_export
    self.option_widgets[self.OPTIONS.DEFAULT_PATH].get_text(),  # type: ignore[attr-defined]
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'default_path'`
I don't know what this means or what I'm looking at, is there anyway to fix? I'm running Fedora 38 and I built it, not using flatpak.

**Comment by actionless** [comment]
this particular error you showing probably happened after recent plugin API update

i haven't been updating or testing the arc plugin since it's not working anyway: https://github.com/themix-project/themix-gui/issues/293
