### ISSUE TITLE
"Export theme" option doesn't work

### ISSUE THREAD

**Issue by arcturus713** [themix-project/themix-gui#490]
"Themix/Oomox Theme Designer" version 1.15.1. Flatpak pulled from the Linux Mint software manager.
I've created a theme, and it looks all nice and dandy, but I can't export it. Clicking "Export Theme..." brings up a menu with a checklist for generating themes for Cinnamon, GNOME Shell, and Xfwm. I can click all of them, I can click none of them, but whatever I do, clicking "Apply Options and Export" yields nothing. I go to the .themes folder where created themes are supposedly exported to. Nothing is there.

**Comment by actionless** [comment]
I can't reproduce the problem with normal build, please report it for flatpak build itself (i can't move the tickets because it belongs to a different organization): 
https://github.com/flathub/com.github.themix_project.Oomox/issues
