### ISSUE TITLE
Error patching uxtheme.dll

### ISSUE THREAD

**Issue by golam71** [themix-project/themix-gui#518]
so i am using the themix-full-git AUR package from archlinux (latest)
everything was working fine but then 
when i do 
```
⋊> ~ bash /opt/oomox/plugins/theme_oomox/change_color.sh  /opt/oomox/scripted_colors/xresources/xresources-reverse 
```
i get the error 

```
Error patching uxtheme.dll

Building theme at /home/golam71/.themes/oomox-xresources-reverse
```
and all the themes like xresources xresourses-reverse are affected they dont look like what they should 
this is how they should look like 
![image](https://github.com/themix-project/themix-gui/assets/74001687/8421099b-2640-429d-9543-29f0557eeec7)

as u can see the preview on the right side
then u see the error as mentioned 
![image](https://github.com/themix-project/themix-gui/assets/74001687/7023d353-58e7-4d74-874d-25b0554e42d2)

the theme even after setting does not even look close
![image](https://github.com/themix-project/themix-gui/assets/74001687/40a7cf49-4b1e-4a70-aa42-4d420537a76a)

any help regrading the issue would be helpful 
please note that this was mentioned before here but the solution was not given

**Comment by golam71** [comment]
also icons were unaffected by this

**Comment by actionless** [comment]
try re-installing your Windows XP if your uxtheme.dll is corrupted

**Comment by golam71** [comment]
> try re-installing your Windows XP if your uxtheme.dll is corrupted

bro i am on archlinux

**Comment by golam71** [comment]
@actionless

**Comment by golam71** [comment]
![image](https://github.com/themix-project/themix-gui/assets/74001687/2cfb395e-4744-4099-a24b-efe81d1031e5)

**Comment by actionless** [comment]
idk then 🤷

**Comment by golam71** [comment]
rebuilding the package from scracth and a full system update and upgrade 
along with reboot now fixes the issue
(it was not before)
