### ISSUE TITLE
Color for selected items in Thunar is the same as the background color

### ISSUE THREAD

**Issue by lancemgiles** [themix-project/themix-gui#519]
When I select a folder or a file in Thunar, the only color that changes is on the icon. This itself isn't a problem, and with most files and folders, it is still apparent, though subtle, that something has been selected, assuming that your textbox background color is not white. But with files that have transparent backgrounds, there is no indication that the file has been selected.

I thought this was maybe an issue with the color scheme I chose, but I tried a few presets and they have this same behavior. In Nemo, the item's name is highlighted with the selected text color, so it seems to be specific to Thunar.

It could be problem with my setup, but if not, I thought it was worth sharing. (Arch, no DE just Openbox). I haven't been able to find anything when I search online about this.

**Comment by actionless** [comment]
that's a repo of the gui app, not of one of the themes

**Comment by lancemgiles** [comment]
I understand this the repo for the guitar app, but I guess I'm confused.
I've used the gui app to make themes and I have this issue in all of them,
so I thought it was a bug in the app.

**Comment by lancemgiles** [comment]
Gui*
